### ISSUE TITLE
Fixing seperate dependencies for nodePackages

### ISSUE THREAD

**Issue by samjwillis97** [PrimaMateria/blog-neovim-nix#1]
Hey, firstly, great blog post, was very informative and a massive help for starting my own neovim-flake.

When I saw your problem with `nodePackages` I did some digging and found this blog post: https://ertt.ca/blog/2022/01-12-nix-symlinkJoin-nodePackages.

I made the required changes on my neovim-flake here: https://github.com/samjwillis97/neovim-flake/blob/81e3327000a1bcb4d59025156bf350e775671ded/packages/myNeovim.nix#L11

This now lets me have all the runtime dependencies in a single set. 

And another thing, I got the `flake-utils` working to generate an output for `x86_64-linux`, `x86_64-darwin`, `aarch64-linux`, `aarch64-darwin`. It can be found here if you're interested in that: https://github.com/samjwillis97/neovim-flake/blob/81e3327000a1bcb4d59025156bf350e775671ded/flake.nix

I was trying to make a PR for these but lost the battle with `git-crypt` and secrets.

**Comment by PrimaMateria** [comment]
Thank you, I really appreciate your message. I will have a look on your changes probably next week, and I will let you know how it went.

**Comment by PrimaMateria** [comment]
Thank you, I really appreciate your message. I will have a look on your changes probably next week, and I will let you know how it went.

**Comment by PrimaMateria** [comment]
Thank you, I really appreciate your message. I will have a look on your changes probably next week, and I will let you know how it went.

**Comment by PrimaMateria** [comment]
A little bit late, but finally I found energy to update it according to your comment. I posted new article: https://primamateria.github.io/blog/neovim-nix-update/
One more time, thanks for the help.
